version: '3'
services:
  quay:
    image: docker.io/zhangchl007/quay:devel
    container_name: quay
    restart: always
    privileged: true
    sysctls:
      - net.core.somaxconn=4096
    volumes:
      - /quay/config:/conf/stack:Z
      - /quay/storage:/datastorage:Z
    networks:
      - quay
    ports:
      - 443:8443
    environment:
      - DEBUGLOG=false
      - ENCRYPTED_ROBOT_TOKEN_MIGRATION_PHASE=new-installation
    depends_on:
      - mysql
      - redis
  mysql:
    image: registry.access.redhat.com/rhscl/mysql-57-rhel7
    container_name: mysql
    restart: always
    privileged: true
    volumes:
      - /var/lib/mysql:/var/lib/mysql/data:Z
    networks:
      - quay
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=redhat
      - MYSQL_DATABASE=enterpriseregistrydb
      - MYSQL_USER=quayuser
      - MYSQL_PASSWORD=redhat
  redis:
    image: registry.access.redhat.com/rhscl/redis-32-rhel7
    container_name: redis
    restart: always
    privileged: true
    volumes:
      - /var/lib/redis:/var/lib/redis/data:Z
    networks:
      - quay
    ports:
      - 6379:6379
    depends_on:
      - mysql
networks:
  quay:
    external: false
